### ISSUE TITLE
DQD missing favicon

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/qualitydashboard#32]
![Image](https://github.com/user-attachments/assets/b1949811-7376-4cae-9ede-145f36f50b6d)

**Comment by michaelwood** [comment]
Is this a cache issue, we thought this was addressed in https://github.com/ThreeSixtyGiving/qualitydashboard/issues/19  the site title in the screenshot also is different from current live.

On my browsers (chromium based) :

![Image](https://github.com/user-attachments/assets/d2f79fa8-3891-40d7-b426-14b60119791a)

**Comment by mariongalley** [comment]
It's still missing for me in current live in Chrome

![Image](https://github.com/user-attachments/assets/68ca25ba-5cf9-454c-8c33-3f3960acc9a7)

Can it still be cached since we fixed it in November 2024?

**Comment by mariongalley** [comment]
It does appear for me in Firefox though

![Image](https://github.com/user-attachments/assets/fd7b1401-65b3-4da8-840c-f6c1692594d2)

**Comment by mariongalley** [comment]
Working for me at the moment, closing issue
